networks:
  {{ USERNAME }}-cassandra-net:

services:
  {{ USERNAME }}-cassandra-1:
    image: cassandra:4.1.4
    container_name: {{ USERNAME }}-cassandra-1
    networks: [{{ USERNAME }}-cassandra-net]
    ports:
      - "0:9042"
      - "0:8080"
    environment:
      - CASSANDRA_CLUSTER_NAME={{ USERNAME }}-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC={{ USERNAME }}-DC
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_SEEDS={{ USERNAME }}-cassandra-1
    volumes:
      - {{ USERNAME }}-cassandra-node-1:/var/lib/cassandra:rw
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 4m
      timeout: 10s
      retries: 5

  {{ USERNAME }}-cassandra-2:
    image: cassandra:4.1.4
    container_name: {{ USERNAME }}-cassandra-2
    networks: [{{ USERNAME }}-cassandra-net]
    environment:
      - CASSANDRA_CLUSTER_NAME={{ USERNAME }}-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC={{ USERNAME }}-DC
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_SEEDS={{ USERNAME }}-cassandra-1
    depends_on:
      - {{ USERNAME }}-cassandra-1
    volumes:
      - {{ USERNAME }}-cassandra-node-2:/var/lib/cassandra:rw
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 4m
      timeout: 10s
      retries: 5

  {{ USERNAME }}-cassandra-3:
    image: cassandra:4.1.4
    container_name: {{ USERNAME }}-cassandra-3
    networks: [{{ USERNAME }}-cassandra-net]
    environment:
      - CASSANDRA_CLUSTER_NAME={{ USERNAME }}-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC={{ USERNAME }}-DC
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_SEEDS={{ USERNAME }}-cassandra-1
    depends_on:
      - {{ USERNAME }}-cassandra-2
    volumes:
      - {{ USERNAME }}-cassandra-node-3:/var/lib/cassandra:rw
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 4m
      timeout: 10s
      retries: 5

volumes:
  {{ USERNAME }}-cassandra-node-1:
  {{ USERNAME }}-cassandra-node-2:
  {{ USERNAME }}-cassandra-node-3:
